---
- hosts: all
  tasks:
  - name: i want to ping my webserver
    ping:
  - name: i want to install apache2 webserver on ubuntu
    apt:
      name: apache2
      state: present
  - name: i want to start my apache2 webserver
    service:
      name: apache2
      state: started